version: '3.1'
services:
  redis:
    image: bitnami/redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: spring
    volumes:
      - redis-data:/var/spring-redis-data-example/redis
volumes:
  redis-data:
